# NumPy

NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of NumPy, focusing on arrays and vectorized operations.

#### (1) Basic code

In [2]:
import numpy as np
arr1=np.array([1,2,3])#1-D array
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3]
<class 'numpy.ndarray'>
(3,)


#### (2) 1-D array
Understanding braces

1-D array have 1 braces open and 1 closed

2-D array have 2 braces open and 2 closed 

3-D array have 3 braces open and 3 closed

in output
 

In [3]:
arr2=np.array([1,2,3,4,5])
arr2 = arr2.reshape(1,5)#reshaping to 1 row and 5 coloumn
print(arr2.shape)

(1, 5)


#### (3) list inside list

In [4]:

arr3=np.array([[1,2,3,4,5]])#Used list inside a list
arr3.shape

(1, 5)

#### (4) 2-D array
Here we have 2 Rows and 5 coloums

In [5]:

arr3=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr3)
print(arr3.shape)#returns 2 rows and 5 coloums

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


#### (5) Inbuilt methods


(a) arange()


In [6]:
arr6=np.arange(0,10,2)#2 is skip step parameter
# start = 0
# stop  = 10 (excluded)
# step  = 2

arr7=np.arange(0,12,2).reshape(2,3)#reshape into 5 row and 1 coloum
print(arr6)
print(arr7)

[0 2 4 6 8]
[[ 0  2  4]
 [ 6  8 10]]


(b) ones() :- Used to create array with all elements as one

In [7]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

(c) eye() :- will help to create identity matrix

In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

(d) Other methods

In [9]:
arr = np.array([[1,2,3],[4,5,6]])

print("Array:", arr)
print("Shape:", arr.shape)
print("Number of dimension:", arr.ndim)
print("Size(number of elements):", arr.size)
print("Data type:", arr.dtype)
print("Item size(in bytes):", arr.itemsize)

Array: [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimension: 2
Size(number of elements): 6
Data type: int64
Item size(in bytes): 8


#### (6) NumPy Vectorized Operation: 
Every operation we will perform will be applied Element wise

(a) Basic Operations

In [10]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

#Element-wise operations
print("Addition:", arr1+arr2)
print("Substraction:", arr1-arr2)
print("Multiplication:", arr1*arr2)
print("Division:", arr1/arr2)

Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


(b) Operations using Universal Functions

In [11]:
arr = np.array([10,20,30,40,50])

print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))
print(np.log(arr))

[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]
[2.20264658e+04 4.85165195e+08 1.06864746e+13 2.35385267e+17
 5.18470553e+21]
[-0.54402111  0.91294525 -0.98803162  0.74511316 -0.26237485]
[2.30258509 2.99573227 3.40119738 3.68887945 3.91202301]


(c) Compute Row wise and Column wise sum

In [12]:
arr =np.arange(1,17).reshape(4,4)
# Row wise sum 
print(arr.sum(axis=1))
# Column wise sum 
print(arr.sum(axis=0))

[10 26 42 58]
[28 32 36 40]


(d) Broadcasting

In [13]:
#Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations, by automatically expanding the smaller array to match the shape of the larger array.
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.array([1,3,5])
arr3 = arr + arr2
print("Original Array:\n", arr)
print("Array to be broadcasted:\n", arr2)
print("Result after broadcasting:\n", arr3)

Original Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Array to be broadcasted:
 [1 3 5]
Result after broadcasting:
 [[ 2  5  8]
 [ 5  8 11]
 [ 8 11 14]]


#### (7) Array Slicing and Indexing
(a) arr[row][coloum]

In [14]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array: \n",arr)
print(arr[0][0]) #1
print(arr[2][1]) #10

print(arr[1:,2:])# [row 1 to empty means last row , coloum 2 to empty means last coloum] 
print(arr[0:2,2:])#[row 0 to row 2(means row before 2= 1), coloum 2 to empty means last coloum]
print(arr[1:,1:3])

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1
10
[[ 7  8]
 [11 12]]
[[3 4]
 [7 8]]
[[ 6  7]
 [10 11]]


(b) Modify array elements

In [15]:

arr[0][0]=100
print(arr)#element at index 0,0 will be replaced by 100

arr[1:]=100
print(arr)#all the element from row 1 to last row which is row 2 will be replaced by 100

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


#### (8) Statistical Concept:-  Normalization
(a) Normalization is converting data in such a way that your mean is 0 and standard deviation is 1

In [16]:
#To have a mean of 0 and standard deviation of 1
data = np.array([1,2,3,4,5])

#Calculating mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

#Normalize the data 
normalized_data = (data - mean) / std_dev
print("Normalized data:", normalized_data)



Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


(2) Calculating Mean, Meadian, Standard deviation and Variance

In [17]:
data = np.array([1,2,3,4,5,6,7,8,9])

#Mean
mean = np.mean(data)
print("Mean:", mean)

#Median
median = np.median(data)
print("Median:", median)

#Standard deviation 
std_dev = np.std(data)
print("Standard deviation:", std_dev)

#Variance
variance = np.var(data)
print("Variance:", variance)

Mean: 5.0
Median: 5.0
Standard deviation: 2.581988897471611
Variance: 6.666666666666667


#### (9) Logical Operations

In [18]:
data = np.array([1,2,3,4,5,6,7,8,9])

print(data>5) #return boolean output
print(data[data>5]) #return which elements are greater then 5

print(data[(data>=5) & (data<=8)])
print(data[(data<3) | (data>7)])

[False False False False False  True  True  True  True]
[6 7 8 9]
[5 6 7 8]
[1 2 8 9]


#### (10)

In [1]:
!pip install matplotlib

  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.1 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.1 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.1 MB 782.7 kB/s eta 0:00:10
   --- ------------------------------------ 0.8/8.1 MB 927.7 kB/s eta 0:00:08
   ------ --------------------------------- 1.3/8.1 MB 1.3 MB/s eta 0:00:06
   ------- -------------------------------- 1.6/8.1 MB 1.3 MB/s eta 0:00:06
   --------- ------------------------------ 1.8/8.1 MB 1.3 MB/s eta 0:00:05
   ----------- ---------------------------- 2.4/8.1 MB 1.5 MB/s eta 0:00:04
   ------------ --------------------------- 2.6/8.1 MB 1.5 MB/s eta 0:00:04
   --------------- ------------------------ 3.1/8.1 MB 1.5 MB/s eta 0:00:04
   ------------------ --------------------- 3.7/8.1 MB 1.6 MB/s eta 0:00:03
   -------------------- -----------------