In [8]:
import numpy as np 
arr=np.array([1,2,3,4,5])
arr
print(type(arr))
print(arr.shape)

<class 'numpy.ndarray'>
(5,)


In [12]:
arr1=np.array([1,2,3,4,5,6])

arr2 = arr1.reshape(2,3)
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
arr5 = np.arange(1,8)
arr5

array([1, 2, 3, 4, 5, 6, 7])

In [19]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])